In [1]:
pip install fastf1

Collecting fastf1
  Downloading fastf1-3.5.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: matplotlib<4.0.0,>=3.5.1 in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (3.9.2)
Requirement already satisfied: numpy<3.0.0,>=1.23.1 in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.4.1 in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (2.2.2)
Requirement already satisfied: python-dateutil in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.12.2-cp312-cp312-win_amd64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: requests>=2.28.1 in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.8.1 in c:\users\dorot\anaconda3\lib\site-packages (from fastf1) (1.13.1)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Collecting websockets<14,>=10.3 (from fastf1)
  Downloading websockets-13.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dorot\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.5.1->fastf1) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dorot\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dorot\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.4.1->fastf1) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dorot\anaconda3\lib\site-packages (from python-dateutil->fastf1) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dorot\anaconda3\lib\site-packages (from requests>=2.28.1->fastf1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dorot\anaconda3\lib\site-packages (from requests>=2.28.1->fastf1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dorot\anaconda3\lib\site-packages (from requests>=2.28.1->fastf1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dorot\anaconda3\lib\site-packages (from requests>=2.28.1->fastf1) (2025.1.31)
Requirement already satisfied: attrs>=21.2 in c:\users\dorot\anaconda3\lib\site-packages (from requests-cache>=1.0.0->fastf1) (25.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\dorot\anaconda3\lib\site-packages (from requests-cache>=1.0.0->fastf1) (3.10.0)
Collecting url-normalize>=1.4 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Downloading fastf1-3.5.3-py3-none-any.whl (151 kB)
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading websockets-13.1-cp312-cp312-win_amd64.whl (159 kB)
Downloading rapidfuzz-3.12.2-cp312-cp312-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 8.7 MB/s eta 0:00:00
Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: websockets, url-normalize, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-24.1.2 fastf1-3.5.3 rapidfuzz-3.12.2 requests-cache-1.2.1 timple-0.1.8 url-normalize-1.4.3 websockets-13.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import fastf1

In [5]:
import os
cache_folder='cache_folder'
if not os.path.exists(cache_folder):
    os.makedirs(cache_folder)
fastf1.Cache.enable_cache(cache_folder)

In [8]:
from fastf1.events import get_event_schedule
schedule = get_event_schedule(2025)
schedule.head()

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2025,2025-02-28,Pre-Season Testing,testing,Practice 1,2025-02-26 10:00:00+03:00,2025-02-26 07:00:00,...,Practice 3,2025-02-28 10:00:00+03:00,2025-02-28 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Australia,Melbourne,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,Australian Grand Prix,conventional,Practice 1,2025-03-14 12:30:00+11:00,2025-03-14 01:30:00,...,Practice 3,2025-03-15 12:30:00+11:00,2025-03-15 01:30:00,Qualifying,2025-03-15 16:00:00+11:00,2025-03-15 05:00:00,Race,2025-03-16 15:00:00+11:00,2025-03-16 04:00:00,True
2,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025,2025-03-23,Chinese Grand Prix,sprint_qualifying,Practice 1,2025-03-21 11:30:00+08:00,2025-03-21 03:30:00,...,Sprint,2025-03-22 11:00:00+08:00,2025-03-22 03:00:00,Qualifying,2025-03-22 15:00:00+08:00,2025-03-22 07:00:00,Race,2025-03-23 15:00:00+08:00,2025-03-23 07:00:00,True
3,3,Japan,Suzuka,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2025,2025-04-06,Japanese Grand Prix,conventional,Practice 1,2025-04-04 11:30:00+09:00,2025-04-04 02:30:00,...,Practice 3,2025-04-05 11:30:00+09:00,2025-04-05 02:30:00,Qualifying,2025-04-05 15:00:00+09:00,2025-04-05 06:00:00,Race,2025-04-06 14:00:00+09:00,2025-04-06 05:00:00,True
4,4,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2025,2025-04-13,Bahrain Grand Prix,conventional,Practice 1,2025-04-11 14:30:00+03:00,2025-04-11 11:30:00,...,Practice 3,2025-04-12 15:30:00+03:00,2025-04-12 12:30:00,Qualifying,2025-04-12 19:00:00+03:00,2025-04-12 16:00:00,Race,2025-04-13 18:00:00+03:00,2025-04-13 15:00:00,True

In [104]:
session=fastf1.get_session(2025,'Australia','Q')
session.load()

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

In [105]:
aus_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
aus_quali['GrandPrix']='Australian Grand Prix'
aus_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
4,1.0,NOR,McLaren,0 days 00:01:15.912000,0 days 00:01:15.415000,0 days 00:01:15.096000,Australian Grand Prix
81,2.0,PIA,McLaren,0 days 00:01:16.062000,0 days 00:01:15.468000,0 days 00:01:15.180000,Australian Grand Prix
1,3.0,VER,Red Bull Racing,0 days 00:01:16.018000,0 days 00:01:15.565000,0 days 00:01:15.481000,Australian Grand Prix
63,4.0,RUS,Mercedes,0 days 00:01:15.971000,0 days 00:01:15.798000,0 days 00:01:15.546000,Australian Grand Prix
22,5.0,TSU,Racing Bulls,0 days 00:01:16.225000,0 days 00:01:16.009000,0 days 00:01:15.670000,Australian Grand Prix

In [108]:
laps = session.laps.pick_quicklaps()
sector_times_aus_quali = laps[['Driver','LapNumber' ,'LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_aus_quali['GrandPrix']='Australian Grand Prix'
sector_times_aus_quali

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,NOR,2.0,0 days 00:01:16.003000,0 days 00:00:26.383000,0 days 00:00:17.285000,0 days 00:00:32.335000,Australian Grand Prix
4,NOR,5.0,0 days 00:01:15.912000,0 days 00:00:26.463000,0 days 00:00:17.116000,0 days 00:00:32.333000,Australian Grand Prix
9,NOR,10.0,0 days 00:01:15.556000,0 days 00:00:26.104000,0 days 00:00:17.122000,0 days 00:00:32.330000,Australian Grand Prix
12,NOR,13.0,0 days 00:01:15.415000,0 days 00:00:26.194000,0 days 00:00:17.030000,0 days 00:00:32.191000,Australian Grand Prix
15,NOR,16.0,0 days 00:01:15.921000,0 days 00:00:26.127000,0 days 00:00:17.057000,0 days 00:00:32.737000,Australian Grand Prix
...,...,...,...,...,...,...,...
278,HUL,8.0,0 days 00:01:16.579000,0 days 00:00:26.656000,0 days 00:00:17.201000,0 days 00:00:32.722000,Australian Grand Prix
281,LAW,2.0,0 days 00:01:17.094000,0 days 00:00:26.819000,0 days 00:00:17.362000,0 days 00:00:32.913000,Australian Grand Prix
288,OCO,2.0,0 days 00:01:17.517000,0 days 00:00:27.066000,0 days 00:00:17.337000,0 days 00:00:33.114000,Australian Grand Prix
291,OCO,5.0,0 days 00:01:17.147000,0 days 00:00:26.686000,0 days 00:00:17.206000,0 days 00:00:33.255000,Australian Grand Prix
294,OCO,8.0,0 days 00:01:17.686000,0 days 00:00:26.678000,0 days 00:00:17.331000,0 days 00:00:33.677000,Australian Grand Prix

In [110]:
session=fastf1.get_session(2025,'Australia','R')
session.load()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

In [111]:
aus_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
aus_race['GrandPrix']='Australian Grand Prix'
aus_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
4,1.0,NOR,McLaren,0 days 01:42:06.304000,Finished,Australian Grand Prix
1,2.0,VER,Red Bull Racing,0 days 00:00:00.895000,Finished,Australian Grand Prix
63,3.0,RUS,Mercedes,0 days 00:00:08.481000,Finished,Australian Grand Prix
12,4.0,ANT,Mercedes,0 days 00:00:10.135000,Finished,Australian Grand Prix
23,5.0,ALB,Williams,0 days 00:00:12.773000,Finished,Australian Grand Prix

In [112]:
session=fastf1.get_session(2025,'China','Q')
session.load()

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']

In [113]:
china_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
china_quali['GrandPrix']='Chinese Grand Prix'
china_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
81,1.0,PIA,McLaren,0 days 00:01:31.591000,0 days 00:01:31.200000,0 days 00:01:30.641000,Chinese Grand Prix
63,2.0,RUS,Mercedes,0 days 00:01:31.295000,0 days 00:01:31.307000,0 days 00:01:30.723000,Chinese Grand Prix
4,3.0,NOR,McLaren,0 days 00:01:30.983000,0 days 00:01:30.787000,0 days 00:01:30.793000,Chinese Grand Prix
1,4.0,VER,Red Bull Racing,0 days 00:01:31.424000,0 days 00:01:31.142000,0 days 00:01:30.817000,Chinese Grand Prix
44,5.0,HAM,Ferrari,0 days 00:01:31.690000,0 days 00:01:31.501000,0 days 00:01:30.927000,Chinese Grand Prix

In [114]:
laps = session.laps.pick_quicklaps()
sector_times_china_quali = laps[['Driver','LapNumber' ,'LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_china_quali['GrandPrix']='Chinese Grand Prix'
sector_times_china_quali.head()

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,PIA,2.0,0 days 00:01:31.591000,0 days 00:00:24.176000,0 days 00:00:27.442000,0 days 00:00:39.973000,Chinese Grand Prix
4,PIA,5.0,0 days 00:01:31.927000,0 days 00:00:24.252000,0 days 00:00:27.538000,0 days 00:00:40.137000,Chinese Grand Prix
9,PIA,10.0,0 days 00:01:31.200000,0 days 00:00:24.219000,0 days 00:00:27.341000,0 days 00:00:39.640000,Chinese Grand Prix
12,PIA,13.0,0 days 00:01:31.245000,0 days 00:00:24.103000,0 days 00:00:27.315000,0 days 00:00:39.827000,Chinese Grand Prix
15,PIA,16.0,0 days 00:01:30.703000,0 days 00:00:23.984000,0 days 00:00:27.163000,0 days 00:00:39.556000,Chinese Grand Prix

In [115]:
session=fastf1.get_session(2025,'China','R')
session.load()

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

In [116]:
china_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
china_race['GrandPrix']='Chinese Grand Prix'
china_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
81,1.0,PIA,McLaren,0 days 01:30:55.026000,Finished,Chinese Grand Prix
4,2.0,NOR,McLaren,0 days 00:00:09.748000,Finished,Chinese Grand Prix
63,3.0,RUS,Mercedes,0 days 00:00:11.097000,Finished,Chinese Grand Prix
1,4.0,VER,Red Bull Racing,0 days 00:00:16.656000,Finished,Chinese Grand Prix
31,5.0,OCO,Haas F1 Team,0 days 00:00:49.969000,Finished,Chinese Grand Prix

In [117]:
session=fastf1.get_session(2025,'Japan','Q')
session.load()

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']

In [118]:
japan_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
japan_quali['GrandPrix']='Japanese Grand Prix'
japan_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
1,1.0,VER,Red Bull Racing,0 days 00:01:27.943000,0 days 00:01:27.502000,0 days 00:01:26.983000,Japanese Grand Prix
4,2.0,NOR,McLaren,0 days 00:01:27.845000,0 days 00:01:27.146000,0 days 00:01:26.995000,Japanese Grand Prix
81,3.0,PIA,McLaren,0 days 00:01:27.687000,0 days 00:01:27.507000,0 days 00:01:27.027000,Japanese Grand Prix
16,4.0,LEC,Ferrari,0 days 00:01:27.920000,0 days 00:01:27.555000,0 days 00:01:27.299000,Japanese Grand Prix
63,5.0,RUS,Mercedes,0 days 00:01:27.843000,0 days 00:01:27.400000,0 days 00:01:27.318000,Japanese Grand Prix

In [119]:
laps = session.laps.pick_quicklaps()
sector_times_japan_quali = laps[['Driver', 'LapNumber','LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_japan_quali['GrandPrix']='Japanese Grand Prix'
sector_times_japan_quali.head()

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,VER,2.0,0 days 00:01:28.360000,0 days 00:00:30.856000,0 days 00:00:40.015000,0 days 00:00:17.489000,Japanese Grand Prix
4,VER,5.0,0 days 00:01:27.943000,0 days 00:00:30.696000,0 days 00:00:39.718000,0 days 00:00:17.529000,Japanese Grand Prix
7,VER,8.0,0 days 00:01:27.502000,0 days 00:00:30.510000,0 days 00:00:39.641000,0 days 00:00:17.351000,Japanese Grand Prix
12,VER,13.0,0 days 00:01:27.278000,0 days 00:00:30.463000,0 days 00:00:39.463000,0 days 00:00:17.352000,Japanese Grand Prix
15,VER,16.0,0 days 00:01:26.983000,0 days 00:00:30.387000,0 days 00:00:39.355000,0 days 00:00:17.241000,Japanese Grand Prix

In [120]:
session=fastf1.get_session(2025,'Japan','R')
session.load()

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']

In [121]:
japan_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
japan_race['GrandPrix']='Japanese Grand Prix'
japan_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
1,1.0,VER,Red Bull Racing,0 days 01:22:06.983000,Finished,Japanese Grand Prix
4,2.0,NOR,McLaren,0 days 00:00:01.423000,Finished,Japanese Grand Prix
81,3.0,PIA,McLaren,0 days 00:00:02.129000,Finished,Japanese Grand Prix
16,4.0,LEC,Ferrari,0 days 00:00:16.097000,Finished,Japanese Grand Prix
63,5.0,RUS,Mercedes,0 days 00:00:17.362000,Finished,Japanese Grand Prix

In [122]:
session=fastf1.get_session(2025,'Bahrain','Q')
session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']

In [123]:
bahrain_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
bahrain_quali['GrandPrix']='Bahrain Grand Prix'
bahrain_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
81,1.0,PIA,McLaren,0 days 00:01:31.392000,0 days 00:01:30.454000,0 days 00:01:29.841000,Bahrain Grand Prix
63,2.0,RUS,Mercedes,0 days 00:01:31.494000,0 days 00:01:30.664000,0 days 00:01:30.009000,Bahrain Grand Prix
16,3.0,LEC,Ferrari,0 days 00:01:31.454000,0 days 00:01:30.724000,0 days 00:01:30.175000,Bahrain Grand Prix
12,4.0,ANT,Mercedes,0 days 00:01:31.415000,0 days 00:01:30.716000,0 days 00:01:30.213000,Bahrain Grand Prix
10,5.0,GAS,Alpine,0 days 00:01:31.462000,0 days 00:01:30.643000,0 days 00:01:30.216000,Bahrain Grand Prix

In [124]:
laps = session.laps.pick_quicklaps()
sector_times_bahrain_quali = laps[['Driver', 'LapNumber','LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_bahrain_quali['GrandPrix']='Bahrain Grand Prix'
sector_times_bahrain_quali.head()

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,PIA,2.0,0 days 00:01:31.392000,0 days 00:00:29.287000,0 days 00:00:39.300000,0 days 00:00:22.805000,Bahrain Grand Prix
7,PIA,8.0,0 days 00:01:30.454000,0 days 00:00:28.883000,0 days 00:00:38.853000,0 days 00:00:22.718000,Bahrain Grand Prix
10,PIA,11.0,0 days 00:01:30.233000,0 days 00:00:28.902000,0 days 00:00:38.771000,0 days 00:00:22.560000,Bahrain Grand Prix
13,PIA,14.0,0 days 00:01:29.841000,0 days 00:00:28.784000,0 days 00:00:38.574000,0 days 00:00:22.483000,Bahrain Grand Prix
16,RUS,2.0,0 days 00:01:31.941000,0 days 00:00:29.278000,0 days 00:00:39.722000,0 days 00:00:22.941000,Bahrain Grand Prix

In [125]:
session=fastf1.get_session(2025,'Bahrain','R')
session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63: Lap timing integrity check failed for 3 lap(s)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']

In [126]:
bahrain_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
bahrain_race['GrandPrix']='Bahrain Grand Prix'
bahrain_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
81,1.0,PIA,McLaren,0 days 01:35:39.435000,Finished,Bahrain Grand Prix
63,2.0,RUS,Mercedes,0 days 00:00:15.499000,Finished,Bahrain Grand Prix
4,3.0,NOR,McLaren,0 days 00:00:16.273000,Finished,Bahrain Grand Prix
16,4.0,LEC,Ferrari,0 days 00:00:19.679000,Finished,Bahrain Grand Prix
44,5.0,HAM,Ferrari,0 days 00:00:27.993000,Finished,Bahrain Grand Prix

In [127]:
session=fastf1.get_session(2025,'Saudi Arabia','Q')
session.load()

core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '63', '16', '12', '55', '44', '22', '10', '4', '23', '30', '14', '6', '87', '18', '7', '27', '31', '5']

In [128]:
saudi_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
saudi_quali['GrandPrix']='Saudi Arabian Grand Prix'
saudi_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
1,1.0,VER,Red Bull Racing,0 days 00:01:27.778000,0 days 00:01:27.529000,0 days 00:01:27.294000,Saudi Arabian Grand Prix
81,2.0,PIA,McLaren,0 days 00:01:27.901000,0 days 00:01:27.545000,0 days 00:01:27.304000,Saudi Arabian Grand Prix
63,3.0,RUS,Mercedes,0 days 00:01:28.282000,0 days 00:01:27.599000,0 days 00:01:27.407000,Saudi Arabian Grand Prix
16,4.0,LEC,Ferrari,0 days 00:01:28.552000,0 days 00:01:27.866000,0 days 00:01:27.670000,Saudi Arabian Grand Prix
12,5.0,ANT,Mercedes,0 days 00:01:28.128000,0 days 00:01:27.798000,0 days 00:01:27.866000,Saudi Arabian Grand Prix

In [129]:
laps = session.laps.pick_quicklaps()
sector_times_saudi_quali = laps[['Driver', 'LapNumber','LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_saudi_quali['GrandPrix']='Saudi Arabian Grand Prix'
sector_times_saudi_quali.head()

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,VER,2.0,0 days 00:01:28.148000,0 days 00:00:31.970000,0 days 00:00:27.841000,0 days 00:00:28.337000,Saudi Arabian Grand Prix
4,VER,5.0,0 days 00:01:27.778000,0 days 00:00:31.874000,0 days 00:00:27.813000,0 days 00:00:28.091000,Saudi Arabian Grand Prix
7,VER,8.0,0 days 00:01:27.529000,0 days 00:00:31.710000,0 days 00:00:27.726000,0 days 00:00:28.093000,Saudi Arabian Grand Prix
10,VER,11.0,0 days 00:01:27.940000,0 days 00:00:32.054000,0 days 00:00:27.764000,0 days 00:00:28.122000,Saudi Arabian Grand Prix
14,VER,15.0,0 days 00:01:27.559000,0 days 00:00:31.829000,0 days 00:00:27.714000,0 days 00:00:28.016000,Saudi Arabian Grand Prix

In [130]:
session=fastf1.get_session(2025,'Saudi Arabia','R')
session.load()

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']

In [131]:
saudi_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
saudi_race['GrandPrix']='Saudi Arabian Grand Prix'
saudi_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
81,1.0,PIA,McLaren,0 days 01:21:06.758000,Finished,Saudi Arabian Grand Prix
1,2.0,VER,Red Bull Racing,0 days 00:00:02.843000,Finished,Saudi Arabian Grand Prix
16,3.0,LEC,Ferrari,0 days 00:00:08.104000,Finished,Saudi Arabian Grand Prix
4,4.0,NOR,McLaren,0 days 00:00:09.196000,Finished,Saudi Arabian Grand Prix
63,5.0,RUS,Mercedes,0 days 00:00:27.236000,Finished,Saudi Arabian Grand Prix

In [132]:
session=fastf1.get_session(2025,'Miami','Q')
session.load()

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '12', '81', '63', '55', '23', '16', '31', '22', '6', '44', '5', '7', '30', '27', '14', '10', '18', '87']

In [133]:
miami_quali=session.results[['Position', 'Abbreviation','TeamName', 'Q1', 'Q2', 'Q3']]
miami_quali['GrandPrix']='Miami Grand Prix'
miami_quali.head()

,Position,Abbreviation,TeamName,Q1,Q2,Q3,GrandPrix
1,1.0,VER,Red Bull Racing,0 days 00:01:26.870000,0 days 00:01:26.643000,0 days 00:01:26.204000,Miami Grand Prix
4,2.0,NOR,McLaren,0 days 00:01:26.955000,0 days 00:01:26.499000,0 days 00:01:26.269000,Miami Grand Prix
12,3.0,ANT,Mercedes,0 days 00:01:27.077000,0 days 00:01:26.606000,0 days 00:01:26.271000,Miami Grand Prix
81,4.0,PIA,McLaren,0 days 00:01:27.006000,0 days 00:01:26.269000,0 days 00:01:26.375000,Miami Grand Prix
63,5.0,RUS,Mercedes,0 days 00:01:27.014000,0 days 00:01:26.575000,0 days 00:01:26.385000,Miami Grand Prix

In [134]:
laps = session.laps.pick_quicklaps()
sector_times_miami_quali = laps[['Driver', 'LapNumber','LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']]
sector_times_miami_quali['GrandPrix']='Miami Grand Prix'
sector_times_miami_quali.head()

,Driver,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,GrandPrix
1,VER,2.0,0 days 00:01:27.573000,0 days 00:00:28.784000,0 days 00:00:33.733000,0 days 00:00:25.056000,Miami Grand Prix
4,VER,5.0,0 days 00:01:26.870000,0 days 00:00:28.413000,0 days 00:00:33.450000,0 days 00:00:25.007000,Miami Grand Prix
7,VER,8.0,0 days 00:01:26.643000,0 days 00:00:28.345000,0 days 00:00:33.309000,0 days 00:00:24.989000,Miami Grand Prix
10,VER,11.0,0 days 00:01:26.654000,0 days 00:00:28.339000,0 days 00:00:33.405000,0 days 00:00:24.910000,Miami Grand Prix
13,VER,14.0,0 days 00:01:26.492000,0 days 00:00:28.268000,0 days 00:00:33.245000,0 days 00:00:24.979000,Miami Grand Prix

In [137]:
session=fastf1.get_session(2025,'Miami','R')
session.load()

core           INFO 	Loading data for Miami Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']

In [138]:
miami_race = session.results[['Position', 'Abbreviation', 'TeamName', 'Time', 'Status']]
miami_race['GrandPrix']='Miami Grand Prix'
miami_race.head()

,Position,Abbreviation,TeamName,Time,Status,GrandPrix
81,1.0,PIA,McLaren,0 days 01:28:51.587000,Finished,Miami Grand Prix
4,2.0,NOR,McLaren,0 days 00:00:04.630000,Finished,Miami Grand Prix
63,3.0,RUS,Mercedes,0 days 00:00:37.644000,Finished,Miami Grand Prix
1,4.0,VER,Red Bull Racing,0 days 00:00:39.956000,Finished,Miami Grand Prix
23,5.0,ALB,Williams,0 days 00:00:48.067000,Finished,Miami Grand Prix

In [142]:
aus_quali=aus_quali[(aus_quali['Abbreviation']=='NOR')|(aus_quali['Abbreviation']=='PIA')]
china_quali=china_quali[(china_quali['Abbreviation']=='NOR')|(china_quali['Abbreviation']=='PIA')]
japan_quali=japan_quali[(japan_quali['Abbreviation']=='NOR')|(japan_quali['Abbreviation']=='PIA')]
bahrain_quali=bahrain_quali[(bahrain_quali['Abbreviation']=='NOR')|(bahrain_quali['Abbreviation']=='PIA')]
saudi_quali=saudi_quali[(saudi_quali['Abbreviation']=='NOR')|(saudi_quali['Abbreviation']=='PIA')]
miami_quali=miami_quali[(miami_quali['Abbreviation']=='NOR')|(miami_quali['Abbreviation']=='PIA')]

In [143]:
sector_times_aus_quali=sector_times_aus_quali[(sector_times_aus_quali['Driver']=='NOR')|(sector_times_aus_quali['Driver']=='PIA')]
sector_times_china_quali=sector_times_china_quali[(sector_times_china_quali['Driver']=='NOR')|(sector_times_china_quali['Driver']=='PIA')]
sector_times_japan_quali=sector_times_japan_quali[(sector_times_japan_quali['Driver']=='NOR')|(sector_times_japan_quali['Driver']=='PIA')]
sector_times_bahrain_quali=sector_times_bahrain_quali[(sector_times_bahrain_quali['Driver']=='NOR')|(sector_times_bahrain_quali['Driver']=='PIA')]
sector_times_saudi_quali=sector_times_saudi_quali[(sector_times_saudi_quali['Driver']=='NOR')|(sector_times_saudi_quali['Driver']=='PIA')]
sector_times_miami_quali=sector_times_miami_quali[(sector_times_miami_quali['Driver']=='NOR')|(sector_times_miami_quali['Driver']=='PIA')]

In [144]:
aus_race=aus_race[(aus_race['Abbreviation']=='NOR')|(aus_race['Abbreviation']=='PIA')]
china_race=china_race[(china_race['Abbreviation']=='NOR')|(china_race['Abbreviation']=='PIA')]
japan_race=japan_race[(japan_race['Abbreviation']=='NOR')|(japan_race['Abbreviation']=='PIA')]
bahrain_race=bahrain_race[(bahrain_race['Abbreviation']=='NOR')|(bahrain_race['Abbreviation']=='PIA')]
saudi_race=saudi_race[(saudi_race['Abbreviation']=='NOR')|(saudi_race['Abbreviation']=='PIA')]
miami_race=miami_race[(miami_race['Abbreviation']=='NOR')|(miami_race['Abbreviation']=='PIA')]

In [92]:
import pandas as pd

In [170]:
aus_quali.to_csv('aus_quali.csv')
china_quali.to_csv('china_quali.csv')
japan_quali.to_csv('japan_quali.csv')
bahrain_quali.to_csv('bahrain_quali.csv')
saudi_quali.to_csv('saudi_quali.csv')
miami_quali.to_csv('miami_quali.csv')

In [172]:
sector_times_aus_quali.to_csv('sector_times_aus_quali.csv')
sector_times_china_quali.to_csv('sector_times_china_quali.csv')
sector_times_japan_quali.to_csv('sector_times_japan_quali.csv')
sector_times_bahrain_quali.to_csv('sector_times_bahrain_quali.csv')
sector_times_saudi_quali.to_csv('sector_times_saudi_quali.csv')
sector_times_miami_quali.to_csv('sector_times_miami_quali.csv')

In [174]:
aus_race.to_csv('aus_race.csv')
china_race.to_csv('china_race.csv')
japan_race.to_csv('japan_race.csv')
bahrain_race.to_csv('bahrain_race.csv')
saudi_race.to_csv('saudi_race.csv')
miami_race.to_csv('miami_race.csv')

In [21]:
results['Time'] = results['Time'].apply(lambda x: str(x).split()[-1])
results.head()

C:\Users\dorot\AppData\Local\Temp\ipykernel_15724\980954602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results['Time'] = results['Time'].apply(lambda x: str(x).split()[-1])

,Position,DriverNumber,Abbreviation,TeamName,Time,Status
4,1.0,4,NOR,McLaren,01:42:06.304000,Finished
1,2.0,1,VER,Red Bull Racing,00:00:00.895000,Finished
63,3.0,63,RUS,Mercedes,00:00:08.481000,Finished
12,4.0,12,ANT,Mercedes,00:00:10.135000,Finished
23,5.0,23,ALB,Williams,00:00:12.773000,Finished